name: Build iOS (Release)

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS Release
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: |
          npm install

      - name: Generate JS Bundle for iOS
        run: |
          mkdir -p ios/mainjsbundle
          npx react-native bundle \
            --platform ios \
            --dev false \
            --entry-file index.js \
            --bundle-output ios/mainjsbundle/main.jsbundle \
            --assets-dest ios/

      - name: Install CocoaPods
        run: |
          cd ios && pod install --repo-update

      - name: Build iOS App (Release)
        run: |
          cd ios && xcodebuild \
            -workspace youthcube.xcworkspace \
            -scheme your-project-name \
            -sdk iphoneos \
            -configuration Release \
            clean build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_STYLE="Manual" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            CODE_SIGN_ENTITLEMENTS=""

      - name: Archive the app
        run: |
          cd ios && zip -r build/Release-iphoneos/app-release.zip build/Release-iphoneos/youthcube.app

      - name: Upload iOS App as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ios-release
          path: ios/build/Release-iphoneos/app-release.zip
