name: Check iOS Scheme (Dry Run)

on:
  workflow_dispatch:

jobs:
  check-scheme:
    name: Check iOS Scheme and Workspace
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect iOS Scheme
        id: detect_scheme
        working-directory: ios
        run: |
          # 自动查找 .xcworkspace 文件夹
          workspace=$(ls -d *.xcworkspace | head -n 1)

          # 检查 contents.xcworkspacedata 是否存在
          if [ ! -f "$workspace/contents.xcworkspacedata" ]; then
            echo "❌ Error: Missing 'contents.xcworkspacedata' in '$workspace'."
            exit 1
          fi

          # 使用更健壮的方式提取第一个 Scheme 名
          scheme=$(xcodebuild -list -workspace "$workspace" | awk '/^$/ {next} /Schemes:/,/^---/ || NR==FNR+1 {if (!found && $0 !~ /Schemes:/ && $0 != "") {print $0; found=1}}')

          if [ -z "$scheme" ]; then
            echo "❌ Error: No schemes found in the workspace."
            exit 1
          fi

          echo "::set-output name=scheme::$scheme"
          echo "::set-output name=workspace::$workspace"

          echo "✅ Successfully detected:"
          echo "   - Workspace: $workspace"
          echo "   - Scheme: $scheme"
